### ISSUE TITLE
Module parse failed: Unexpected token type Props

### ISSUE THREAD

**Issue by rmeissen** [nicklassvendsrud/react-swipe-to-reveal-actions#6]
I installed as per the documentation, and immediately upon use this is the error I see:

```
./node_modules/react-swipe-to-reveal-actions/SwipeToRevealActions.tsx 5:5
Module parse failed: Unexpected token (5:5)
You may need an appropriate loader to handle this file type.
| import './styles.css';
| 
> type Props = {
|     children: React.ReactNode;
|     actionButtons: {
```

Any suggestions or help appreciated!

**Comment by bvalasek** [comment]
same, tried it in fresh create-react-app and same result and install as per documentation.
I had some issue with this line `Unable to import SwipeToRevealActions, module not found` underCompiler options. When commented out webpack was still unable to compile :

**Comment by nicklassvendsrud** [comment]
Hi! Sorry about this @rmeissen , @bvalasek . Please upgrade to version 1.0.7, and this should be fixed. Thanks!
